### ISSUE TITLE
ExtraBold v6.000 Name ID 2 is set to Bold

### ISSUE THREAD

**Issue by kenmcd** [fontef/frankruhl#11]
ExtraBold v6.000 Name ID 2 is set to `Bold`, and it should be `Regular`.
Fonts taken from this repo today 2022-11-10.
This affects https://github.com/google/fonts/pull/5528

**Comment by meirsadan** [comment]
Cc: @emmamarichal – perhaps you can advise us on this issue?

**Comment by emmamarichal** [comment]
Yes indeed, I had a look to the sources, and the box "bold" in the style linking parameters was checked (in the extrabold instance) and it shouldn't. @meirsadan I send new a PR!
<img width="1260" alt="Capture d’écran 2022-11-11 à 11 13 20" src="https://user-images.githubusercontent.com/64773544/201318560-2d5bf55a-36b4-4d0a-a1e5-0f8489ce1f3c.png">

**Comment by meirsadan** [comment]
Great, thanks so much @emmamarichal 
I will close this issue once we merge the new PR then
