### ISSUE TITLE
Misplaced nikud under double-yud and double-vov digraphs

### ISSUE THREAD

**Issue by markhdavid** [fontef/frankruhl#16]
This font renders digraphs **double-yud** (Unicode Character “װ” (U+05F0) ; Name: Hebrew Ligature Yiddish Double Vav) and **double-vov** (Unicode Character “ײ” (U+05F2) ; Name: Hebrew Ligature Yiddish Double Yod), primarily used for Yiddish, such that nikud that's supposed to be centered under a character get put under the second subletter of the digraph. So a nikud like pasekh, tsere, segol, et al, is centered under the 2nd yud of double-yud and under 2nd vov of double-vov. That's wrong. Nikud is supposed to be centered with respect to both elements of the digraph. That's how these work. That's the whole point of why you need these digraphs. If you wanted the nikud centered under the second character of the digraph, you wouldn't need a digraph: you'd put out two separate characters with the nikud following the second character in the character sequence and unambiguously intended to be centered under that second character.

Here's a sample text for which I'll attach a screen shot of Google Fonts preview showing wrong rendering: װֶעלְכֶע | װֶעלְן | זײַן | רײַך
![Google Fonts Frank Ruhl - bad double-yud and double-vov digraphs - Screen Shot 2023-03-17 at 4 26 01 PM](https://user-images.githubusercontent.com/6209504/226069106-01a8bc9d-b4f6-4a64-adf7-0fc32ef5cf62.png)

**Comment by markhdavid** [comment]
For comparison here is a screen shot of the same preview text in the Google font named *Arimo*. 
![Arimo font with double-yud and double-vov with nikud at Google Fonts - Screen Shot 2023-03-21 at 5 52 40 PM](https://user-images.githubusercontent.com/6209504/226774220-d4b2395f-4587-48a7-af35-172e982a4467.png)

**Comment by fontef** [comment]
@emmamarichal Can you please help us re-generate the font files based on the latest fixes?

**Comment by emmamarichal** [comment]
Hi @fontef! 
Yes sure. The issues you solved are the same that in the @markhdavid's PRs?
Just to know if these PRs should be closed or merged. 

Tell me when all is good and I'll start to review. I'm going to open an issue to update the font :)

**Comment by fontef** [comment]
Hi @emmamarichal!
@markhdavid’s PRs should be closed.

All good, you can update the font :)
