### ISSUE TITLE
Copyright notice should match files and LICENSE.txt and be ascii

### ISSUE THREAD

**Issue by davelab6** [fontef/frankruhl#2]
Currently the copyright notice is,

> Copyright (c) 2014 Monotype Imaging Inc. (licensing@monotype.com). All Rights Reserved. David Hadash is a trademark of Monotype Imaging Inc. Reserved Font Name 'Hadash'. Copyright (c) 2003-2008 SIL International (http://www.sil.org/), with Reserved Font Names 'Gentium' and 'SIL'. Copyright (c) 2015-2016 Meir Sadan (meir@sadan.com). 

This is a bit long! :) Its also possible to set things up as per https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#ofltxt to make it easier to add more contributors later ([example](https://github.com/NDISCOVER/Arima-Font))

**Comment by davelab6** [comment]
I will make a pull request to address this

**Comment by davelab6** [comment]
Oh! This is from David Hofshi.

**Comment by fontef** [comment]
I see this is done. Should we also add an AUTHOR.txt file with the proper credits?

**Comment by davelab6** [comment]
Yes please :)
