### ISSUE TITLE
Vertical Metrics

### ISSUE THREAD

**Issue by davelab6** [fontef/frankruhl#4]
Currently the vertical metrics are set for desktop installations, but this will cause clipping on the web:

```
$ fontbakery-fix-vertical-metrics.py *ttf
Parameter              FrankRuhlHofshi-Black.ttf    FrankRuhlHofshi-Bold.ttf    FrankRuhlHofshi-Light.ttf    FrankRuhlHofshi-Medium.ttf    FrankRuhlHofshi-Regular.ttf    
ymax                   932                          942                         940                          957                           947                            
hhea.ascent            1000                         1000                        1000                         1000                          1000                           
OS/2.sTypoAscender     800                          800                         800                          800                           800                            
OS/2.usWinAscent       1000                         1000                        1000                         1000                          1000                           
ymin                   -334                         -322                        -280                         -303                          -289                           
hhea.descent           -200                         -200                        -200                         -200                          -200                           
OS/2.sTypoDescender    -200                         -200                        -200                         -200                          -200                           
OS/2.usWinDescent      200                          200                         200                          200                           200                            
hhea.lineGap           0                            0                           0                            0                             0                              
OS/2.sTypoLineGap      200                          200                         200                          200                           200                            
hhea total             1200                         1200                        1200                         1200                          1200                           
typo total             1200                         1200                        1200                         1200                          1200                           
win total              1200                         1200                        1200                         1200                          1200                           
UPM:Heights            1000:1266                    1000:1264                   1000:1220                    1000:1260                     1000:1236                      
UPM:Heights %          126 %                        126 %                       122 %                        126 %                         123 %                          

Low Glyphs
FrankRuhlHofshi-Black.ttf: kcommaaccent Kcommaaccent uni0327 ccedilla gcommaaccent uni05C7 Eogonek ygrave ogonek Scedilla cedilla ydieresis ncommaaccent Ncommaaccent g uni05BD uni05BB Rcommaaccent uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 Aogonek Ccedilla lcommaaccent uni0162 uni0163 yacute Uogonek uni05B0 Scommaaccent uni0328 gbreve Lcommaaccent uniFB2F ycircumflex uni0326 y aogonek uni00B5 eogonek scommaaccent uni021A uni021B rcommaaccent uogonek Iogonek J iogonek j scedilla
FrankRuhlHofshi-Bold.ttf: kcommaaccent Kcommaaccent uni0327 ccedilla gcommaaccent uni05C7 Eogonek ygrave ogonek Scedilla cedilla ydieresis ncommaaccent Ncommaaccent g uni05BD uni05BB Rcommaaccent uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 Aogonek Ccedilla lcommaaccent uni0162 uni0163 yacute Uogonek uni05B0 Scommaaccent uni0328 gbreve Lcommaaccent uniFB2F ycircumflex uni0326 y aogonek uni00B5 eogonek scommaaccent uni021A uni021B rcommaaccent uogonek Iogonek J iogonek j scedilla
FrankRuhlHofshi-Light.ttf: gcommaaccent uni05C7 ygrave ydieresis exclamdown g uni05BD uni05BB uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 yacute questiondown uni05B0 gbreve uniFB2F ycircumflex y uni00B5 J j
FrankRuhlHofshi-Medium.ttf: kcommaaccent Kcommaaccent uni0327 ccedilla gcommaaccent uni05C7 Eogonek ygrave ogonek Scedilla cedilla ydieresis ncommaaccent exclamdown Ncommaaccent g uni05BD uni05BB Rcommaaccent uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 Aogonek Ccedilla lcommaaccent uni0162 uni0163 yacute Uogonek uni05B0 Scommaaccent uni0328 gbreve Lcommaaccent uniFB2F ycircumflex uni0326 y aogonek uni00B5 eogonek scommaaccent uni021A uni021B rcommaaccent uogonek Iogonek J iogonek j scedilla
FrankRuhlHofshi-Regular.ttf: gcommaaccent uni05C7 ygrave ydieresis exclamdown g uni05BD uni05BB uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 yacute questiondown uni05B0 gbreve uniFB2F ycircumflex y uni00B5 J j
```

The details should be:

```
$ fontbakery-fix-vertical-metrics.py *ttf.fix
Parameter              FrankRuhlHofshi-Black.ttf.fix    FrankRuhlHofshi-Bold.ttf.fix    FrankRuhlHofshi-Light.ttf.fix    FrankRuhlHofshi-Medium.ttf.fix    FrankRuhlHofshi-Regular.ttf.fix    
ymax                   932                              942                             940                              957                               947                                
hhea.ascent            957                              957                             957                              957                               957                                
OS/2.sTypoAscender     957                              957                             957                              957                               957                                
OS/2.usWinAscent       957                              957                             957                              957                               957                                
ymin                   -334                             -322                            -280                             -303                              -289                               
hhea.descent           -334                             -334                            -334                             -334                              -334                               
OS/2.sTypoDescender    -334                             -334                            -334                             -334                              -334                               
OS/2.usWinDescent      334                              334                             334                              334                               334                                
hhea.lineGap           0                                0                               0                                0                                 0                                  
OS/2.sTypoLineGap      0                                0                               0                                0                                 0                                  
hhea total             1291                             1291                            1291                             1291                              1291                               
typo total             1291                             1291                            1291                             1291                              1291                               
win total              1291                             1291                            1291                             1291                              1291                               
UPM:Heights            1000:1266                        1000:1264                       1000:1220                        1000:1260                         1000:1236                          
UPM:Heights %          126 %                            126 %                           122 %                            126 %                             123 %                              
```

You can set Glyphs customParameters on the masters for each of the 6 vertical metrics values and the 2 linegap values

**Comment by fontef** [comment]
I'll ask Meir to help me tomorrow with all this technical stuff as I'm
clueless

On Wednesday, 2 March 2016, Dave Crossland notifications@github.com wrote:

> Currently the vertical metrics are set for desktop installations, but this
> will cause clipping on the web:
> 
> $ fontbakery-fix-vertical-metrics.py *ttf
> Parameter              FrankRuhlHofshi-Black.ttf    FrankRuhlHofshi-Bold.ttf    FrankRuhlHofshi-Light.ttf    FrankRuhlHofshi-Medium.ttf    FrankRuhlHofshi-Regular.ttf
> ymax                   932                          942                         940                          957                           947
> hhea.ascent            1000                         1000                        1000                         1000                          1000
> OS/2.sTypoAscender     800                          800                         800                          800                           800
> OS/2.usWinAscent       1000                         1000                        1000                         1000                          1000
> ymin                   -334                         -322                        -280                         -303                          -289
> hhea.descent           -200                         -200                        -200                         -200                          -200
> OS/2.sTypoDescender    -200                         -200                        -200                         -200                          -200
> OS/2.usWinDescent      200                          200                         200                          200                           200
> hhea.lineGap           0                            0                           0                            0                             0
> OS/2.sTypoLineGap      200                          200                         200                          200                           200
> hhea total             1200                         1200                        1200                         1200                          1200
> typo total             1200                         1200                        1200                         1200                          1200
> win total              1200                         1200                        1200                         1200                          1200
> UPM:Heights            1000:1266                    1000:1264                   1000:1220                    1000:1260                     1000:1236
> UPM:Heights %          126 %                        126 %                       122 %                        126 %                         123 %
> 
> Low Glyphs
> FrankRuhlHofshi-Black.ttf: kcommaaccent Kcommaaccent uni0327 ccedilla gcommaaccent uni05C7 Eogonek ygrave ogonek Scedilla cedilla ydieresis ncommaaccent Ncommaaccent g uni05BD uni05BB Rcommaaccent uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 Aogonek Ccedilla lcommaaccent uni0162 uni0163 yacute Uogonek uni05B0 Scommaaccent uni0328 gbreve Lcommaaccent uniFB2F ycircumflex uni0326 y aogonek uni00B5 eogonek scommaaccent uni021A uni021B rcommaaccent uogonek Iogonek J iogonek j scedilla
> FrankRuhlHofshi-Bold.ttf: kcommaaccent Kcommaaccent uni0327 ccedilla gcommaaccent uni05C7 Eogonek ygrave ogonek Scedilla cedilla ydieresis ncommaaccent Ncommaaccent g uni05BD uni05BB Rcommaaccent uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 Aogonek Ccedilla lcommaaccent uni0162 uni0163 yacute Uogonek uni05B0 Scommaaccent uni0328 gbreve Lcommaaccent uniFB2F ycircumflex uni0326 y aogonek uni00B5 eogonek scommaaccent uni021A uni021B rcommaaccent uogonek Iogonek J iogonek j scedilla
> FrankRuhlHofshi-Light.ttf: gcommaaccent uni05C7 ygrave ydieresis exclamdown g uni05BD uni05BB uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 yacute questiondown uni05B0 gbreve uniFB2F ycircumflex y uni00B5 J j
> FrankRuhlHofshi-Medium.ttf: kcommaaccent Kcommaaccent uni0327 ccedilla gcommaaccent uni05C7 Eogonek ygrave ogonek Scedilla cedilla ydieresis ncommaaccent exclamdown Ncommaaccent g uni05BD uni05BB Rcommaaccent uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 Aogonek Ccedilla lcommaaccent uni0162 uni0163 yacute Uogonek uni05B0 Scommaaccent uni0328 gbreve Lcommaaccent uniFB2F ycircumflex uni0326 y aogonek uni00B5 eogonek scommaaccent uni021A uni021B rcommaaccent uogonek Iogonek J iogonek j scedilla
> FrankRuhlHofshi-Regular.ttf: gcommaaccent uni05C7 ygrave ydieresis exclamdown g uni05BD uni05BB uni05B8 uni05B2 uni05B3 uni05B1 uni05B6 yacute questiondown uni05B0 gbreve uniFB2F ycircumflex y uni00B5 J j
> 
> The details should be:
> 
> $ fontbakery-fix-vertical-metrics.py *ttf.fix
> Parameter              FrankRuhlHofshi-Black.ttf.fix    FrankRuhlHofshi-Bold.ttf.fix    FrankRuhlHofshi-Light.ttf.fix    FrankRuhlHofshi-Medium.ttf.fix    FrankRuhlHofshi-Regular.ttf.fix
> ymax                   932                              942                             940                              957                               947
> hhea.ascent            957                              957                             957                              957                               957
> OS/2.sTypoAscender     957                              957                             957                              957                               957
> OS/2.usWinAscent       957                              957                             957                              957                               957
> ymin                   -334                             -322                            -280                             -303                              -289
> hhea.descent           -334                             -334                            -334                             -334                              -334
> OS/2.sTypoDescender    -334                             -334                            -334                             -334                              -334
> OS/2.usWinDescent      334                              334                             334                              334                               334
> hhea.lineGap           0                                0                               0                                0                                 0
> OS/2.sTypoLineGap      0                                0                               0                                0                                 0
> hhea total             1291                             1291                            1291                             1291                              1291
> typo total             1291                             1291                            1291                             1291                              1291
> win total              1291                             1291                            1291                             1291                              1291
> UPM:Heights            1000:1266                        1000:1264                       1000:1220                        1000:1260                         1000:1236
> UPM:Heights %          126 %                            126 %                           122 %                            126 %                             123 %
> 
> You can set Glyphs customParameters on the masters for each of the 6
> vertical metrics values and the 2 linegap values
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fontef/frankruhlhofshi/issues/4.

## 

yanek iontef
+972 (3) 560 5801
www.fontef.com

```
   __o
```

 _ -\  <, _
( \* ) / ( \* )

```

http://bicyclog.wordpress.com/
```

**Comment by davelab6** [comment]
All good! I am fixing things as I go, I'll make a pull request and Meir can merge it :) 

BTW the github messages are emailed to you and anyone who clicks 'watch' at the top of your project, and your email replies to these messages are posted publicly on the Github issue (eg https://github.com/fontef/frankruhlhofshi/issues/4) so you may like to set up a email filter to be sure you know when your reply will become public

**Comment by fontef** [comment]
;~}

On Wednesday, 2 March 2016, Dave Crossland notifications@github.com wrote:

> All good! I am fixing things as I go, I'll make a pull request and Meir
> can merge it :)
> 
> BTW the github messages are emailed to you and anyone who clicks 'watch'
> at the top of your project, and your email replies to these messages are
> posted publicly on the Github issue (eg #4
> https://github.com/fontef/frankruhlhofshi/issues/4) so you may like to
> set up a email filter to be sure you know when your reply will become public
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fontef/frankruhlhofshi/issues/4#issuecomment-191361881
> .

## 

yanek iontef
+972 (3) 560 5801
www.fontef.com

```
   __o
```

 _ -\  <, _
( \* ) / ( \* )

```

http://bicyclog.wordpress.com/
```

**Comment by fontef** [comment]
This looks resolved :>
