### ISSUE TITLE
fsType should be 0

### ISSUE THREAD

**Issue by davelab6** [fontef/frankruhl#5]
Each file has a fsType of 8 today, it should be zero. 

Here is how to set it:

<img width="685" alt="screen shot 2016-03-02 at 01 53 22" src="https://cloud.githubusercontent.com/assets/261579/13470117/8ea1caec-e078-11e5-9561-2af774a592c0.png">

**Comment by fontef** [comment]
Probably also resolved

**Comment by davelab6** [comment]
Was fixed in 4c8a3de
 :)
